version: "2"
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(dmc)
        - blank
        - dot
        - alias
      no-inline-comments: false
      no-prefix-comments: false
      custom-order: true
      no-lex-order: false
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: "interface{}"
          replacement: "any"
    gofumpt:
      extra:
        group-params: true
        clothe-returns: true
        balance-calls: true
    golines:
      max-len: 100
      tab-len: 4
      shorten-comments: false
      reformat-tags: true
      chain-split-dots: true
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
  new: false
  new-from-merge-base: ""
  new-from-rev: ""
  new-from-patch: ""
  whole-files: true
  fix: true
severity:
  default: error