// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sensor.sql

package sqlc

import (
	"context"
)

const createSensorData = `-- name: CreateSensorData :exec
INSERT INTO sensor_data (temperature, humidity, created_at)
VALUES (?, ?, ?)
`

type CreateSensorDataParams struct {
	Temperature float64
	Humidity    float64
	CreatedAt   string
}

func (q *Queries) CreateSensorData(ctx context.Context, arg CreateSensorDataParams) error {
	_, err := q.db.ExecContext(ctx, createSensorData, arg.Temperature, arg.Humidity, arg.CreatedAt)
	return err
}
